import type { Metadata } from "next"

import fonts from "@/lib/fonts"

import { TooltipProvider } from "@/components/ui/tooltip"

import "./globals.css"

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const fontsStringify = fonts.map((font) => font.variable).join(" ")

  return (
    <html lang="en">
      <body className={`${fontsStringify} font-geist antialiased`}>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  )
}
